version: '3.8'

services:

  notebook:
    build: ./notebook
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/data
      - ./public:/home/jovyan/public
      - ./notebook/work:/home/jovyan/work

  scratch:
    build: .
    volumes:
      - ./data:/data
      - ./scripts:/scripts

networks:
  default:
    attachable: true

