version: '3.8'

services:

  notebook:
    build: ./notebook
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/data
      - ./public:/home/jovyan/public
      - ./notebook/work:/home/jovyan/work

  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nih-reporter-watchdog
      #volumes:
      #- ./data/postgresql:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/app:/app

  scratch:
    build: .
    volumes:
      - ./data:/data
      - ./scripts:/scripts

networks:
  default:
    attachable: true

