# Generated by Django 5.1.7 on 2025-03-27 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('appl_id', models.IntegerField()),
                ('project_num', models.CharField(max_length=64)),
                ('fain', models.CharField(max_length=11, null=True)),
                ('date_of_last_change', models.DateTimeField(null=True)),
                ('data_hash', models.TextField()),
                ('data', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['appl_id'], name='reporter_pr_appl_id_fb13cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectRecordChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_of_change', models.DateTimeField()),
                ('flag', models.CharField(choices=[('ALT', 'Altered'), ('RED', 'Reduced'), ('INC', 'Increased'), ('DEL', 'Deleted')], max_length=3)),
                ('field', models.TextField(null=True)),
                ('data', models.JSONField(null=True)),
                ('project_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.projectrecord')),
            ],
        ),
    ]
